# name: changesets
#
# on:
#   push:
#     branches:
#       - main
#
# concurrency: ${{ github.workflow }}-${{ github.ref }}
#
# jobs:
#   version:
#     runs-on: ubuntu-latest
#     permissions: write-all
#     outputs:
#       published: ${{ steps.changesets.outputs.published }}
#     steps:
#       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
#
#       - uses: pnpm/action-setup@v4
#         with:
#           version: 9.15.4
#           run_install: false
#       - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
#         with:
#           node-version: 20
#           cache: pnpm
#
#       - run: pnpm i
#
#       - name: create release pull request
#         id: changesets
#         uses: changesets/action@v1
#         with:
#           version: pnpm ci:version
#           publish: pnpm ci:publish
#           commit: "chore: update versions"
#           title: "chore: update versions"
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
